version: 2

jobs:
  build:
    working_directory: ~/bt-build-base
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            set -x
            tag=0.1.$CIRCLE_BUILD_NUM
            echo "Tag is $tag"
            docker build -t "steshaw/bt-build-base:$tag" .
            docker login -username "$DOCKER_USERNAME" -p "$(echo $DOCKER_PASSWORD_BASE64 | base64 -d)"
            docker push steshaw/bt-build-base:$TAG
            docker images
