version: 2

jobs:
  build:
    working_directory: ~/bt-build-base
    docker:
      - image: docker
    steps:
      - checkout
      - run: |
          pwd
          ls
          which docker
          docker images
